### ISSUE TITLE
Does not pass egui color test

### ISSUE THREAD

**Issue by derivator** [setzer22/godot-egui#14] opened 2021-09-15 10:26 UTC
![Screenshot from 2021-09-15 12-22-43](https://user-images.githubusercontent.com/2171264/133416767-fdba5ce9-808e-4535-afb2-b1fc6cf56d73.png)

[Expected result](https://emilk.github.io/egui/#colors): all gradients except the naive versions match.

**Comment by jacobsky** [comment] 2021-09-15 11:03
This is probably an issue related to either how Godot is translating the vertex texture data or to our translation later. I can confirm that this issue is still present on the latest version of Godot egui in this, but I'm not 100% sure how to solve it.

Any assistance would be greatly appreciated.

**Comment by jacobsky** [comment] 2021-09-15 11:36
I will incorporate this test into the demos, I think it would be useful to keep close at hand so that we can track this issue. I'll also take a look into the color conversion code.

**Comment by derivator** [comment] 2021-09-15 11:36
I'm looking into it right now. I think I found one issue already.

**Comment by jacobsky** [comment] 2021-09-15 12:59
When I dug into the painting code I found a few issues. One is related to a regression from master where I removed the rect clipping when I was trying to fix the `pixels_per_point` setting as well as another issue related to the mesh indicies using 32 bit indicies, when Godot only supports 16 bit indicies.

I also managed to get it looking a _bit_ better by changing the to the following:

```rust
pub fn egui2color(c: egui::Color32) -> Color {
    let (r, g, b, a) = egui::Rgba::from(c).to_tuple();
    Color::from_rgba(r, g, b, a)
}

```

**Comment by jacobsky** [comment] 2021-09-15 13:02
If you are interested in seeing where I'm at with my changes, feel free to take a look a [my repo here](https://github.com/jacobsky/godot-egui/tree/color_test)

**Comment by derivator** [comment] 2021-09-15 13:59
> I also managed to get it looking a _bit_ better by changing the to the following:

Yes, that fixes the interpolation of the vertex colors but makes everything too dark. Blending of transparent colors in front of background is also still wrong. I managed to fix that by setting a material for the canvas items and setting the blend mode with
```rust
material.set_blend_mode(CanvasItemMaterial::BLEND_MODE_PREMULT_ALPHA);
```

The darkness is somewhat confusing to me though. It seems that this is the step that is missing:

- Turn on sRGBA/linear framebuffer if available (GL_FRAMEBUFFER_SRGB).
- Otherwise: gamma-encode the colors before you write them again.

However, if Godot assumes vertex colors to be in linear space (as the interpolation fix suggests) then I would assume it should convert them to sRGB for rendering automatically?

**Comment by derivator** [comment] 2021-09-15 14:09
> However, if Godot assumes vertex colors to be in linear space then I would assume it should convert them to sRGB for rendering automatically?

This seems to indeed be a [bug in Godot](https://github.com/godotengine/godot/issues/48039):

>Yes. However, if all my inputs are srgb encoded, all the calculations will be incorrectly done in srgb and my result will be bogus but in srgb.
But then if I mark the texture as srgb=enable, it will get darkened. The rgb 188,188,188 will be correctly moved to 0.5, linear encoding achieved. All math will become possible. But then Godot won't convert the linear output to srgb, so either I will copy a conversion function from the internet or I will get a visually wrong result.

**Comment by derivator** [comment] 2021-09-15 17:39
Applying this shader to the canvas items fixes the darkness, but screws up the blending again:
```glsl
shader_type canvas_item;
render_mode blend_premul_alpha;

vec4 from_linear(vec4 linearRGB)
{
    bvec3 cutoff = lessThan(linearRGB.rgb, vec3(0.0031308));
    vec3 higher = vec3(1.055)*pow(linearRGB.rgb, vec3(1.0/2.4)) - vec3(0.055);
    vec3 lower = linearRGB.rgb * vec3(12.92);

    return vec4(mix(higher, lower, cutoff), linearRGB.a);
}

void fragment(){
  COLOR = texture(TEXTURE, UV) * COLOR;
  COLOR = from_linear(COLOR);
}
```

At this point I'm a little stumped...

**Comment by jacobsky** [comment] 2021-09-15 23:30
Thanks for the shader! It helps with a number of the color tests, but it looks like there might be a mistake in how the text is being rendered. It looks like there's an issue differentiating between the background color and the text color.
![image](https://user-images.githubusercontent.com/1459514/133526114-4c28928b-bd90-4b2e-ac54-b6d8b2d50588.png)
![image](https://user-images.githubusercontent.com/1459514/133526159-92b88791-00f6-4ed1-96cc-9eafe9a337c8.png)

**Comment by derivator** [comment] 2021-09-16 00:08
Oh yeah, I have a fix for that as well:
```rust
let pixels: ByteArray = egui_texture.srgba_pixels(1.0).map(|c| [c.r(), c.g(), c.b(), c.a()]).flatten().collect();
```

Documentation for [create_from_image](https://docs.rs/gdnative/0.9.3/gdnative/api/struct.ImageTexture.html#method.create_from_image) says:
>An sRGB to linear color space conversion can take place

so it seems like we have to use srgba_pixels() here. I'm not entirely sure what's happening though, because the text looks crispest if in the shader you then do ```COLOR = linear_from_srgba(texture(TEXTURE, UV)) * COLOR;```, so it seems to be converted back to sRGB before it reaches the shader? Or maybe it's because the blending is still not right, I don't even know anymore...

**Comment by jacobsky** [comment] 2021-09-16 02:45
Ah! That helped a bunch. I was able to get this in my last go around.

![image](https://user-images.githubusercontent.com/1459514/133540892-dce1d55e-9337-433b-808c-8b808a1f0348.png)

Oddly enough, setting the blend_mode results in text that more accurately follows the egui demo, but it causes failing for other color tests.

![image](https://user-images.githubusercontent.com/1459514/133541059-e58cf37d-5397-4159-9c22-cc838481bf5a.png)

**Comment by jacobsky** [comment] 2021-09-16 08:58
@derivator I've been playing around with it today. And I think that we are pretty close to getting this correct. One thing that I've found is that this is enough to get the color tests to pass.

```glsl
shader_type canvas_item;
render_mode blend_premul_alpha, unshaded;

void fragment(){
	COLOR = texture(TEXTURE, UV) * COLOR;
}
```

I haven't been successful in adjusting the gamma. I think this shader is required to do the proper blending over the egui node.

The only remaining task is to figure out how to adjust the gamma levels without breaking the rest of the stuff.

**Comment by derivator** [comment] 2021-09-16 11:18
>The only remaining task is to figure out how to adjust the gamma levels without breaking the rest of the stuff.

Yes, that is the problem. Doing linear->sRGB conversion in the shader fixes the brightness, but breaks the blending, I assume because blending is done after the fragment shader. Maybe the solution could be a post-processing shader applied to just the output of godot-egui, leaving everything else the way it is. But I don't know enough about godot to say how that would be accomplished.

**Comment by jacobsky** [comment] 2021-09-17 00:50
@derivator I opened a draft PR with my current progress in making these changes.

From my understanding the core of the issue is related to Godot only supporting linear space as well as the shader configuration only supporting a subset of Open Gl's configuration options. I think that Godot's blend mode doesn't quite match the `(ONE, ONE_MINUS_SRC_ALPHA)` that egui expects from open GL.

Either way, the current changes have improved the visuals of egui quite a bit and are a lot closers to the actual demo pages. So I think even without the perfect blending, it's a lot more consistent across the board.

**Comment by derivator** [comment] 2021-09-17 11:28
>I think that Godot's blend mode doesn't quite match the (ONE, ONE_MINUS_SRC_ALPHA) that egui expects from open GL.

I think the blending is fine if you stay in linear color space, but if you do the linear -> sRGB conversion in the fragment shader it is blending the wrong thing (the sRGB colors, while it should blend the linear colors).

The missing piece is 
>Turn on sRGBA/linear framebuffer if available (GL_FRAMEBUFFER_SRGB). 

which would do the conversion *after* blending. See [this](https://www.khronos.org/opengl/wiki/Framebuffer):

>If GL_FRAMEBUFFER_SRGB is enabled however, then if the destination image is in the sRGB colorspace [...] then it will assume the shader's output is in the linear RGB colorspace. It will therefore convert the output from linear RGB to sRGB. 

But yeah, what we have is probably better than nothing.

Btw would appreciate if you could [tag me as co-author](https://docs.github.com/en/github/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) in the commit :)

**Comment by jacobsky** [comment] 2021-09-18 01:07
@derivator I will be sure to add you as the co-author. Thank you for all the assistance with this issue!

I also agree, it is likely that if we can turn on the sRGBA/linear framebuffer, Instead we end up doing the conversion by hand which causes some of the colors to go out of whack.

I might do a little more research, if there's a switch somewhere that we could flip to resolve this completely that would be awesome.

**Comment by jacobsky** [comment] 2021-09-18 02:15
From what I can see, it looks like they have support for this only in 3D, so it won't work for GUI nodes since those are CanvasItems. For fun, I tried applying a spatial shader to the canvasitem and it didn't work. :rofl:

Anyways. I'll wrap up work on this PR and include you as a co-author. Hopefully we can get some eyes on it so that we can review the current PRs and I can work on getting them merged and publish a new version of the crate :)

**Comment by jacobsky** [comment] 2021-09-18 04:00
@derivator So, I was cleaning up my commit today and I decided to take one last look at the code. It turns out we are doing everything correctly. When you compare the "ground truth" with the srgb naive implementation, it becomes apparent that you solved this issue with your firth couple of corrections and the shader. Anyways, this fix should be good to go now. Not sure why the "ground truth" is coming up incorrect after color correction though 🤔 

![image](https://user-images.githubusercontent.com/1459514/133871794-c5a5b173-9492-441e-8217-4ec1fc29221c.png)

**Comment by derivator** [comment] 2021-09-18 07:16
>  It turns out we are doing everything correctly. When you compare the "ground truth" with the srgb naive implementation, it becomes apparent that you solved this issue with your firth couple of corrections and the shader.

Unfortunately, I think that's wishful thinking :D If you compare to the [demo](https://emilk.github.io/egui/#colors) you'll see that the ground truth looks exactly like our version, while in our version the gradients become very green way too soon...

**Comment by jacobsky** [comment] 2021-09-21 04:51
Ah, I see. After splicing them together, I can see that they don't quite overlap, (except for the Black and white)
![image](https://user-images.githubusercontent.com/1459514/134113277-1e6d3b0f-ea23-4a23-8a93-e3502040afab.png)


Still not sure why they aren't adjusting correctly.

**Closed** 2021-10-30 15:20 UTC
Labels: bug, help wanted
